FROM ubuntu:24.04

# Set noninteractive mode for apt
# Install the common packages.
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes binfmt-support cmake curl gcc g++ git gnupg make python3 sudo swig

# Update package list and install Lua
RUN apt-get update && \
    apt-get install -y lua5.4\*

RUN dpkg --add-architecture arm64

RUN mkdir /tmp/work

# Start interactive Lua REPL by default
CMD ["lua5.4"]