FROM ubuntu:24.04
LABEL Description="This image contains the build environment for the MBS system on Ubuntu 24.04 arm64."
LABEL org.opencontainers.image.source https://github.com/muhkuh-sys/mbs-docker-images

# Set noninteractive mode for apt
# Install the common packages.
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes binfmt-support cmake curl gcc g++ git gnupg make python3 sudo swig

RUN dpkg --add-architecture arm64

RUN mkdir /tmp/work
