FROM ubuntu:18.04
LABEL Description="This image contains the build environment for the MBS system on Ubuntu 18.04 x86_64."

# Install the common packages.
RUN apt-get update
RUN apt-get install --assume-yes curl gcc g++ git gnupg lib32z1 make python2.7 sudo

# Add the repository for the build tools and install the key.
RUN echo 'deb http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/build_opensuse_org_home_docbacardi.list
RUN curl --location --silent http://download.opensuse.org/repositories/home:doc_bacardi/xUbuntu_18.04/Release.key | apt-key add -
RUN apt-get update

# Install the build tools from the new repository.
RUN apt-get install --assume-yes cmake3 gcc-aarch64-linux-gnu g++-aarch64-linux-gnu mingw-w64-mbs swig3

RUN dpkg --add-architecture arm64
RUN sed -i 's/^deb /deb [arch=amd64,i386] /g' /etc/apt/sources.list
RUN echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports bionic main universe" >>/etc/apt/sources.list
RUN apt-get update

# Create a working folder.
RUN mkdir /tmp/work
