FROM ubuntu:24.04

# Install the common packages.

RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes binfmt-support cmake curl gcc g++ git gnupg make python3 sudo swig

# Create a working folder.

RUN mkdir /tmp/work
 

# Update package list and install Lua
RUN apt-get install -y lua5.4 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Start interactive Lua REPL by default
CMD ["lua5.4"]