name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container:
#          IMAGE_NAME: mbs_ubuntu_2004_arm64
#          IMAGE_NAME: mbs_ubuntu_2004_x86
        - name: "20.04 x86_64"
          image: mbs_ubuntu_2004_x86_64
#          IMAGE_NAME: mbs_ubuntu_2204_arm64
#          IMAGE_NAME: mbs_ubuntu_2204_riscv64
        - name: "22.04 x86_64"
          image: mbs_ubuntu_2204_x86_64

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
#    - name: Log in to the Container registry
#      uses: docker/login-action@v3.1.0
#      with:
#        registry: ${{ env.REGISTRY }}
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{env.REGISTRY}}/dockerfile_${{matrix.container.image}}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./dockerfile_${{matrix.container.image}}
        push: false
        tags: ghcr.io/muhkuh-sys/${{matrix.container.image}} ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
